name: "🚀 🟢 Npm Publish Package"

on:
  push:
    branches: [main]

jobs:
  release:
    name: 🚀 Npm Publish
    runs-on: ubuntu-latest

    if: "startsWith(github.event.head_commit.message, 'Release:')"

    strategy:
      matrix:
        node-version: [15.x]
        go-version: [1.16]
    steps:
      - uses: actions/checkout@v2
      - name: 🟢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Export Go
        run: go env -w  GO111MODULE=auto
        working-directory: ./
      - name: Install golang dependencies
        run: go get github.com/Danny-Dasilva/CycleTLS/cycletls && go get github.com/Danny-Dasilva/fhttp && go get github.com/andybalholm/brotli
        working-directory: ./

      - name: Install deps
        run: npm ci --unsafe-perm

        working-directory: ./

      - name: List changes
        run: git status --verbose
        working-directory: ./

      - name: set name
        run: git config --global user.name 'Danny-Dasilva'
      - name: set email
        run: git config --global user.email 'secrets.EMAIL'
      - name: bump version
        run: npm version patch -m "Release"
      - name: Push git
        run: git push

      - name: 🚀 Publish
        run: npm publish
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
